ServerEvents.recipes(event => {
  event.remove({ output: 'createaddition:zinc_sheet' });
  event.remove({ output: 'create:copper_sheet' });
  event.remove({ output: 'create:brass_sheet' });
  event.remove({ output: 'create:iron_sheet' });
  event.remove({ output: 'create:golden_sheet' });
  event.remove({ output: 'ad_astra:etrionic_blast_furnace' });
  event.remove({ output: 'ad_astra:compressor' });
  event.remove({ output: 'immersiveengineering:plate_steel' });
  event.remove({ output: 'immersiveengineering:plate_electrum' });
  event.remove({ output: 'immersiveengineering:plate_aluminum' });
  event.remove({ output: 'immersiveengineering:plate_lead' });
  event.remove({ output: 'immersiveengineering:plate_silver' });
  event.remove({ output: 'immersiveengineering:plate_nickel' });
  event.remove({ output: 'immersiveengineering:plate_uranium' });
  event.remove({ output: 'immersiveengineering:plate_constantan' });
  event.remove({ output: 'ad_astra:desh_plate' });
  event.remove({ output: 'ad_astra:ostrum_plate' });
  event.remove({ output: 'ad_astra:calorite_plate' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'immersiveengineering:wire_steel' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'immersiveengineering:wire_copper' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'immersiveengineering:wire_electrum' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'immersiveengineering:wire_aluminum' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'immersiveengineering:wire_lead' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'createaddition:gold_wire' });
  event.remove({ not: { type: 'createaddition:rolling' }, output: 'createaddition:iron_wire' });
  event.remove({ not: { type: 'create:pressing' }, output: 'immersiveengineering:plate_duroplast' });
  event.remove({ output: 'createaddition:gold_rod', type: 'createaddition:rolling' })
  event.remove({ output: 'createaddition:brass_rod', type: 'createaddition:rolling' })
  event.remove({ output: 'createaddition:copper_rod', type: 'createaddition:rolling' })
  event.remove({ output: 'immersiveengineering:stick_aluminum', type: 'createaddition:rolling' })
  event.remove({ output: 'immersiveengineering:stick_steel', type: 'createaddition:rolling' })
  event.remove({ output: 'immersiveengineering:stick_iron', type: 'createaddition:rolling' })
  event.remove({ output: 'createaddition:electrum_rod', type: 'createaddition:rolling' })
  event.remove({ output: 'createaddition:copper_spool' });
  event.remove({ output: 'createaddition:gold_spool' });
  event.remove({ output: 'createaddition:electrum_spool' });
  event.remove({ output: 'createaddition:festive_spool' });
  event.remove({ output: 'immersiveengineering:wirecoil_copper' });
  event.remove({ output: 'immersiveengineering:wirecoil_electrum' });
  event.remove({ output: 'immersiveengineering:wirecoil_steel' });
  event.remove({ output: 'immersiveengineering:wirecoil_structure_rope' });
  event.remove({ output: 'immersiveengineering:wirecoil_structure_steel' });
  event.remove({ output: 'immersiveengineering:wirecoil_redstone' });
  event.remove({ output: 'ad_astra:fuel_refinery' });
  event.remove({ output: 'immersiveengineering:watermill' });
  event.remove({ output: 'create:large_water_wheel' });
  event.remove({ output: 'immersiveengineering:windmill' });
  event.remove({ output: 'immersiveengineering:conveyor_basic' });
  event.remove({ output: 'immersiveengineering:conveyor_splitter' });
  event.remove({ output: 'immersiveengineering:conveyor_redstone' });
  event.remove({ output: 'immersiveengineering:conveyor_dropper' });
  event.remove({ output: 'immersiveengineering:conveyor_extract' });
  event.remove({ output: 'immersiveengineering:conveyor_vertical' });
  event.remove({ output: 'tfmg:steel_casing' });
  event.remove({ output: 'tfmg:heavy_machinery_casing' });
  event.remove({ output: 'tfmg:coke_oven' });
  event.remove({ output: 'tfmg:hardened_planks' });
  event.remove({ output: 'immersiveengineering:rs_engineering' });
  event.remove({ output: 'immersiveengineering:light_engineering' });
  event.remove({ output: 'immersiveengineering:heavy_engineering' });
  event.remove({ output: 'immersiveengineering:charging_station' });
  event.remove({ output: 'ad_astra:jet_suit' });
  event.remove({ output: 'ad_astra:jet_suit_pants' });
  event.remove({ output: 'ad_astra:jet_suit_boots' });
  event.remove({ output: 'immersiveengineering:duroplast' });
  event.remove({ output: 'immersiveengineering:glider' });
  event.remove({ output: 'ad_astra:desh_cable' });
  event.remove({ output: 'ad_astra:steel_cable' });
  event.remove({ output: 'ad_astra:coal_generator' });
  event.remove({ output: 'ad_astra:water_pump' });
  event.remove({ output: 'ad_astra:energizer' });
  event.remove({ output: 'ad_astra:zip_gun' });
  event.remove({ output: 'immersiveengineering:fluid_pipe' });
  event.remove({ output: 'immersiveengineering:radiator' });
  event.remove({ output: 'createbigcannons:cast_iron_ingot' });
  event.remove({ output: 'alexsmobs:transmutation_table' });
  event.remove({ output: 'immersiveengineering:thermoelectric_generator' });
  event.remove({ output: 'ae2:item_cell_housing' });
  event.remove({ output: 'ad_astra:ostrum_fluid_pipe' });
  event.remove({ output: 'ad_astra:desh_fluid_pipe' });
  event.remove({ output: 'createaddition:portable_energy_interface' });
  event.remove({ output: 'mekanism:digital_miner' });
  
  event.remove({ input: 'immersiveengineering:hammer' });
  
  event.remove({ output: 'sophisticatedbackpacks:pickup_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_pickup_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:filter_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_filter_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:magnet_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_magnet_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:feeding_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_feeding_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:compacting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:void_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_void_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:restock_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_restock_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:deposit_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_deposit_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:refill_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_refill_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:inception_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:everlasting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:smelting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:auto_smelting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:smoking_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:auto_smoking_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:blasting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:auto_blasting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:crafting_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:stonecutter_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_starter_tier' });
  event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_1' });
  event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_2' });
  event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_3' });
  event.remove({ output: 'sophisticatedbackpacks:stack_upgrade_tier_4' });
  event.remove({ output: 'sophisticatedbackpacks:tool_swapper_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_tool_swapper_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:tank_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:battery_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:pump_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:advanced_pump_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:xp_pump_upgrade' });
  event.remove({ output: 'sophisticatedbackpacks:anvil_upgrade' });
 
  event.remove({ output: 'mekanism:hdpe_elytra' });
  event.remove({ output: 'mekanism:upgrade_energy' });
  event.remove({ output: 'mekanism:ultimate_smelting_factory' });
  event.remove({ output: 'mekanism:ultimate_enriching_factory' });
  event.remove({ output: 'mekanism:ultimate_crushing_factory' });
  event.remove({ output: 'mekanism:ultimate_compressing_factory' });
  event.remove({ output: 'mekanism:ultimate_combining_factory' });
  event.remove({ output: 'mekanism:ultimate_purifying_factory' });
  event.remove({ output: 'mekanism:ultimate_injecting_factory' });
  event.remove({ output: 'mekanism:ultimate_infusing_factory' });
  event.remove({ output: 'mekanism:ultimate_sawing_factory' });
  event.remove({ output: 'mekanism:basic_sawing_factory' });
  event.remove({ output: 'mekanism:basic_infusing_factory' });
  event.remove({ output: 'mekanism:basic_injecting_factory' });
  event.remove({ output: 'mekanism:basic_purifying_factory' });
  event.remove({ output: 'mekanism:basic_combining_factory' });
  event.remove({ output: 'mekanism:basic_compressing_factory' });
  event.remove({ output: 'mekanism:basic_crushing_factory' });
  event.remove({ output: 'mekanism:basic_enriching_factory' });
  event.remove({ output: 'mekanism:basic_smelting_factory' });
  event.remove({ output: 'mekanism:advanced_sawing_factory' });
  event.remove({ output: 'mekanism:advanced_infusing_factory' });
  event.remove({ output: 'mekanism:advanced_injecting_factory' });
  event.remove({ output: 'mekanism:advanced_purifying_factory' });
  event.remove({ output: 'mekanism:advanced_combining_factory' });
  event.remove({ output: 'mekanism:advanced_compressing_factory' });
  event.remove({ output: 'mekanism:advanced_crushing_factory' });
  event.remove({ output: 'mekanism:advanced_enriching_factory' });
  event.remove({ output: 'mekanism:advanced_smelting_factory' });
  event.remove({ output: 'mekanism:elite_sawing_factory' });
  event.remove({ output: 'mekanism:elite_infusing_factory' });
  event.remove({ output: 'mekanism:elite_injecting_factory' });
  event.remove({ output: 'mekanism:elite_purifying_factory' });
  event.remove({ output: 'mekanism:elite_combining_factory' });
  event.remove({ output: 'mekanism:elite_compressing_factory' });
  event.remove({ output: 'mekanism:elite_crushing_factory' });
  event.remove({ output: 'mekanism:elite_enriching_factory' });
  event.remove({ output: 'mekanism:elite_smelting_factory' });
  event.remove({ output: 'mekanism:electric_pump' });
  event.remove({ output: 'mekanism:cardboard_box' });
  event.remove({ output: 'mekanism:ultimate_logistical_transporter' });
  event.remove({ output: 'mekanism:elite_logistical_transporter' });
  event.remove({ output: 'mekanism:advanced_logistical_transporter' });
  event.remove({ output: 'mekanism:basic_logistical_transporter' });
  event.remove({ output: 'mekanism:ultimate_universal_cable' });
  event.remove({ output: 'mekanism:elite_universal_cable' });
  event.remove({ output: 'mekanism:advanced_universal_cable' });
  event.remove({ output: 'mekanism:basic_universal_cable' });
  event.remove({ output: 'mekanism:restrictive_transporter' });
  event.remove({ output: 'mekanism:diversion_transporter' });
  event.remove({ output: 'mekanism:ultimate_mechanical_pipe' });
  event.remove({ output: 'mekanism:elite_mechanical_pipe' });
  event.remove({ output: 'mekanism:advanced_mechanical_pipe' });
  event.remove({ output: 'mekanism:basic_mechanical_pipe' });
  event.remove({ output: 'mekanism:logistical_sorter' });
  event.remove({ output: 'mekanism:cardboard_box' });
})